"""add health_score and prefer_healthy

Revision ID: 49224cce3edf
Revises: 29b2af9aa1a1
Create Date: 2026-06-08 17:05:30.025606
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49224cce3edf'
down_revision: Union[str, None] = '29b2af9aa1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('health_score', sa.Integer(), nullable=True, comment='健康分值(0-100)，越高越健康'))
    op.add_column('recommend_preferences', sa.Column('prefer_healthy', sa.Boolean(), nullable=True, comment='偏好健康：健康分高的权重更大'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend_preferences', 'prefer_healthy')
    op.drop_column('dishes', 'health_score')
    # ### end Alembic commands ###
